config:
  dl_location: #Full location to where you are saving the files (must end in '/')
  archive_location: #Full location of where the archive file is (must end in '/')

pushbullet:
  access_token: #Access token to your pushbullet account - leave blank if you do not want it enabled
  message_title: Downloaded
  message_body: Download {song} from {playlist} #The message that you will see - {song} and {playlist} will be replaced with the song and the name of the playlist (see below)

youtube-dl:
  playlist:
    - link: #Full url for the playlist
      name: My playlist # Give a name to your playlist which will be used for the message
    - link: #Follow the same format for multiple playlists
      name:
